from fastapi import APIRouter, Depends, HTTPException
from fastapi.security import OAuth2PasswordRequestForm
from sqlalchemy import select

from src.auth.models import User
from src.auth.schemas import UserCreate, UserResponse, Token
from src.auth.utils import create_access_token, get_password, verify_password
from src.notifications.tasks import send_welcome_email
from src.shared.database import get_async_db
from sqlalchemy.ext.asyncio import AsyncSession

router = APIRouter(prefix="/auth", tags=["Auth"])

@router.post('/register', status_code=201, response_model=UserResponse)
async def createUser(payload: UserCreate, db : AsyncSession = Depends(get_async_db)):
    
    hashed = get_password(password=payload.password)
    
    # check duplicate
    stmt = select(User).where(User.email == payload.email)
    res = await db.execute(stmt)
    existing = res.scalar_one_or_none()
    
    if existing:
        raise HTTPException(status_code=400, detail="Email already registered")
    
    # Hash Password
    user = User(email= payload.email, hashed_password=hashed)
    
    db.add(user)
    await db.commit()
    await db.refresh(user) # populate autogenerated fields like id, created_at
    
    send_welcome_email.delay(email=payload.email)
    return user


@router.post("/token", response_model=Token)
async def login_for_access_token(
    form_data: OAuth2PasswordRequestForm = Depends(),
    db: AsyncSession = Depends(get_async_db)
):
    # 1. Find User
    # Note: OAuth2 form uses 'username', but we treat it as 'email'
    stmt = select(User).where(User.email == form_data.username)
    res = await db.execute(stmt)
    user = res.scalar_one_or_none()

    # 2. Verify Password
    if not user or not verify_password(form_data.password, user.hashed_password):
        raise HTTPException(
            status_code=401,
            detail="Incorrect email or password",
            headers={"WWW-Authenticate": "Bearer"},
        )

    # 3. Create Token
    access_token = create_access_token(data={"sub": user.email})
    return {"access_token": access_token, "token_type": "bearer"}

